version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: demo_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: demo_db

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: demo_keycloak
    environment:
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - "--import-realm"
    volumes:
      - ./keycloak/import-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8080:8080"

  kong-database:
    image: postgres:14
    container_name: kong_db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    restart: unless-stopped
    volumes:
      - kong_db_data:/var/lib/postgresql/data

  kong:
    image: kong:3.5
    container_name: demo_kong
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8000:8000"   # proxy
      - "8443:8443"   # proxy (SSL)
      - "8001:8001"   # admin

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: demo_db
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/demo-realm
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  kong_db_data:
