version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: demo_mongo
    restart: unless-stopped
    ports: ["27017:27017"]

  keycloak-db:
    image: postgres:14
    container_name: demo_keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: demo_keycloak
    command: ["start-dev", "--import-realm"]
    depends_on:
      - keycloak-db
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: secret
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import-realm.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8080:8080"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_app
    depends_on:
      - mongo
      - keycloak
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: demo_db
    ports:
      - "3000:3000"
    restart: unless-stopped

  kong-db:
    image: postgres:13
    container_name: demo_kong_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_db_data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.7-ubuntu
    command: kong migrations bootstrap
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    restart: on-failure

  kong:
    image: kong:3.7-ubuntu
    container_name: demo_kong
    restart: unless-stopped
    depends_on:
      - app
      - keycloak
      - kong-db
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PLUGINS: "bundled,jwt"
    ports:
      - "8081:8000"
      - "8001:8001"

volumes:
  keycloak_db_data:
  kong_db_data: